In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv('spam.csv', encoding='ISO-8859-1')

In [20]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [21]:
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

In [22]:
df

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [23]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [9]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [10]:
## remove the special char, lower-case the char, remove stopwords, stemming:
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]',' ', df['message'][i]) ##remove special ch
    review = review.lower() ## lower case
    review = review.split() ## convert to list
    review = [stemmer.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [60]:
## BOW model -> binary BOW(only 0 & 1):
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500, binary=True)

In [61]:
X = cv.fit_transform(corpus).toarray()

In [62]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [63]:
X.shape

(5572, 1500)

In [15]:
## N-grams implementation:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500, binary=True, ngram_range=(1,2))
X = cv.fit_transform(corpus).toarray()

In [16]:
cv.vocabulary_

{'go': 483,
 'point': 966,
 'crazi': 262,
 'avail': 66,
 'bugi': 131,
 'great': 509,
 'world': 1463,
 'la': 653,
 'cine': 194,
 'got': 505,
 'wat': 1406,
 'ok': 887,
 'lar': 660,
 'joke': 631,
 'wif': 1440,
 'free': 436,
 'entri': 370,
 'wkli': 1456,
 'comp': 226,
 'win': 1443,
 'cup': 271,
 'final': 415,
 'st': 1195,
 'may': 760,
 'text': 1258,
 'receiv': 1027,
 'question': 1004,
 'std': 1203,
 'txt': 1329,
 'rate': 1011,
 'appli': 50,
 'free entri': 439,
 'rate appli': 1012,
 'dun': 347,
 'say': 1089,
 'earli': 351,
 'alreadi': 30,
 'nah': 833,
 'think': 1270,
 'goe': 492,
 'usf': 1373,
 'live': 707,
 'around': 55,
 'though': 1277,
 'freemsg': 443,
 'hey': 552,
 'darl': 282,
 'week': 1421,
 'word': 1460,
 'back': 78,
 'like': 696,
 'fun': 454,
 'still': 1204,
 'xxx': 1484,
 'send': 1110,
 'even': 376,
 'brother': 125,
 'speak': 1185,
 'treat': 1313,
 'per': 929,
 'request': 1049,
 'set': 1118,
 'caller': 153,
 'press': 982,
 'copi': 247,
 'friend': 448,
 'winner': 1447,
 'valu': 1380

In [17]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [25]:
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]',' ', df['message'][i]) ##remove special ch
    review = review.lower() ## lower case
    review = review.split() ## convert to list
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [26]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [27]:
## implementation of TF-IDF:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
tfidf = TfidfVectorizer(max_features=100)

In [31]:
X = tfidf.fit_transform(corpus).toarray()

In [ ]:
import numpy as np


In [32]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])